### PR TITLE
Fix general failure using Edge 18 and add cross browser testing with SauceLabs

### LINKED ISSUE #1241: Layer never loading in latest Win10 and Edge
Hello everyone, 

Just to mention that I am not able to make CARTO-VL load any layer 

Tested on multiples URLs , CARTO-VL Examples , CARTO-VL Editor, localhost etc...

Microsoft EdgeHTML 18.17763
Microsoft Edge 44.17763.1.0

[Edge Screenshot from https://carto.com/developers/carto-vl/examples/#example-check-for-browser-support](https://gyazo.com/e4695ba1a83f0757311c4049d4c3af96)

Can you reproduce ? Thank you

### PR DESCRIPTION
**Pull request by VictorVelarde**
### Fixes #1241

### CODE REVIEW

File: src/renderer/Dataframe.js [hunk 1]
```diff
@@ -134,14 +134,18 @@ export default class Dataframe extends DummyDataframe {
...
-        gl.bindTexture(gl.TEXTURE_2D, this.propertyTex[propertyName]);
-        gl.texImage2D(gl.TEXTURE_2D, 0, gl.ALPHA,
-            width, height, 0, gl.ALPHA, gl.FLOAT,
-            propertiesFloat32Array);
-        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
-        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
-        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
-        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
+
+        if (propertiesFloat32Array) {
```
Comment (rochoa) [inline src/renderer/Dataframe.js]: Are we uploading the properties in another part?

Comment (VictorVelarde) [reply src/renderer/Dataframe.js]: Not that I am aware of, buy I'll check other uses of `gl.texImage2D`

**Comment by VictorVelarde** [comment]
🔝  I did `push -f`, to temporary remove the fix. 

We are going to first catch the Edge 18 error with a new cross browser testing setup (using saucelabs). Once the error breaks the CI, we'll re-apply the fix.

**Comment by VictorVelarde** [comment]
@rochoa @elenatorro 

Finally we have this ready to be merged. This includes the fix but also new tests using selenium & SauceLabs. That has been included as a new job in CircleCI (`test-browsers-saucelabs`).

The tests run currently just on Windows 10 & Edge (latest). We still have some integration issues with tests on macOS, but we'll face them in a different issue.

With this, we should be ready to release a patch.

**Comment by VictorVelarde** [comment]
If you want to run the tests locally, there are some configuration steps at: **test/browsers/browsers.test.md**

@alejandraarri has recently configured her environment to run these tests, so she can help you if you have any problem with it.

File: test/browsers/browsers-target.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
+// See https://wiki.saucelabs.com/display/DOCS/Platform+Configurator# for a list of supported options
+const browsers = [
+    { 'platform': 'Windows 10', 'browserName': 'chrome', 'version': 'latest' },
+    { 'platform': 'Windows 10', 'browserName': 'firefox', 'version': 'latest' },
+    { 'platform': 'Windows 10', 'browserName': 'MicrosoftEdge', 'version': 'latest' }
+
+    // { 'platform': 'macOS 10.14', 'browserName': 'chrome', 'version': 'latest' },
```
Comment (elenatorro) [inline test/browsers/browsers-target.js]: Since these lines are commented because there's still some work to be done as you say in [this comment](https://github.com/CartoDB/carto-vl/pull/1245#issuecomment-466335161), I'd add a `// FIXME` or `// TODO` comment explaining it. What do you think?

File: test/browsers/browsers.test.md [hunk 3]
```diff
@@ -0,0 +1,47 @@
+
+# Cross browser tests
```
Comment (elenatorro) [inline test/browsers/browsers.test.md]: Very nice doc ✨

File: test/browsers/browsers-target.js (hunk 2 above)
Comment (VictorVelarde) [reply test/browsers/browsers-target.js]: For macOS: https://github.com/CartoDB/carto-vl/issues/1272
For Linux, it looks like the SauceLabs support is on very old browsers, not useful for us, so we should remove them

Comment (alejandraarri) [reply test/browsers/browsers-target.js]: Done!

File: package.json [hunk 4]
```diff
@@ -106,6 +107,8 @@
     "test:user:watch": "karma start --no-single-run --auto-watch --browsers ChromeHeadlessNoSandbox test/integration/user/karma.conf.js",
     "test:user:watchc": "karma start --no-single-run --browsers Chrome test/integration/user/karma.conf.js",
     "test:browser": "karma start --no-single-run --browsers Chrome test/unit/karma.conf.js",
+    "test:browsers:connect": "sc -u $SAUCELABS_USER -k $SAUCELABS_KEY -i cartovl-tunnel",
```
Comment (elenatorro) [inline package.json]: In my case, sauce labs is detecting a proxy url automatically and therefore it fails. By adding this flag it gets fixed.

```suggestion
"test:browsers:connect": "sc -u $SAUCELABS_USER -k $SAUCELABS_KEY -i cartovl-tunnel --no-autodetect"
```

**Comment by VictorVelarde** [comment]
I have accepted your suggestion about the proxy
